### ISSUE TITLE
Regression Manager script broken

### ISSUE THREAD

**Issue by raulbehl** [SimpleCPU/SimpleCPU#22]
On the latest master I see the following error while launching the regressionManager.py script - 
```
**********Running tests from: ../hex_gen/tests/test_j_type_instr/hex/**********
Traceback (most recent call last):
  File "regressionManager.py", line 49, in <module>
    main()
  File "regressionManager.py", line 46, in main
    regression()
  File "regressionManager.py", line 37, in regression
    if pc in files:
UnboundLocalError: local variable 'pc' referenced before assignment
```

Can you please take a look at it?

**Comment by raulbehl** [comment]
Fix in 4f28dc6
